/-
Copyright (c) 2026 Dhruv Gupta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dhruv Gupta
-/
import TLT_Proofs.Capacity.Discretization.DenseBaseChangeCapacity

/-!
# The dyadic rationals as the canonical dense numerical base

The dyadic rationals `ℤ[1/2]` form the canonical countable dense numerical base: the subring of `ℚ`
generated by `2⁻¹`. Their image in `ℝ` is dense (the binary grid `{k·2⁻ⁿ}` meets every interval), and
the inclusion is a ring hom, so they instantiate `DenseNumBase`. Concretely, this is the base over which
the float-executed transformer's capacity is computed: every IEEE-754 float value is a dyadic rational,
so the dyadic capacity dominates the executed model's, while equalling the real-ball capacity by
base-change invariance.

## Main definitions

- `Dyadic` — the dyadic rationals, `↥(Subring.closure {(2⁻¹ : ℚ)})`.
- `dyadicToReal` — the ring-hom inclusion into `ℝ`.

## Main results

- `denseRange_dyadicToReal` — the dyadics are dense in `ℝ` (binary-grid rounding).
- `instance : DenseNumBase Dyadic` — the canonical dense base.
-/

/-!
## References
- ℤ[1/2] dyadic ring: density + finite binary expansion (standard; Wikipedia "Dyadic rational").
- Provenance: Classical-instantiation (canonical facts about ℤ[1/2]).
-/

open Metric

noncomputable section

namespace TLT.Capacity

/-- The dyadic rationals `ℤ[1/2]`, as the subring of `ℚ` generated by `2⁻¹`. -/
def DyadicSubring : Subring ℚ := Subring.closure {(2 : ℚ)⁻¹}

/-- The dyadic rationals, the canonical countable dense numerical base. -/
abbrev Dyadic : Type := DyadicSubring

instance : CommRing Dyadic := inferInstance
instance : Countable Dyadic := inferInstance

/-- The inclusion of the dyadics into `ℝ` (through `ℚ`), a ring hom. -/
def dyadicToReal : Dyadic →+* ℝ := (Rat.castHom ℝ).comp DyadicSubring.subtype

theorem dyadicToReal_injective : Function.Injective dyadicToReal := by
  intro a b hab
  exact Subtype.ext (Rat.cast_injective hab)

/-- **The dyadics are dense in `ℝ`.** Round `x` to the binary grid at resolution `2⁻ⁿ` with
`2⁻ⁿ < ε`: `⌊x·2ⁿ⌋·2⁻ⁿ` is a dyadic rational within `2⁻ⁿ` of `x`. -/
theorem denseRange_dyadicToReal : DenseRange (dyadicToReal : Dyadic → ℝ) := by
  rw [Metric.denseRange_iff]
  intro x ε hε
  obtain ⟨n, hn⟩ := exists_pow_lt_of_lt_one hε (by norm_num : (1 : ℝ) / 2 < 1)
  set k : ℤ := ⌊x * 2 ^ n⌋ with hk
  have hmem : ((k : ℚ) * ((2 : ℚ)⁻¹) ^ n) ∈ DyadicSubring :=
    mul_mem (intCast_mem _ k)
      (pow_mem (Subring.subset_closure (Set.mem_singleton _)) n)
  refine ⟨⟨(k : ℚ) * ((2 : ℚ)⁻¹) ^ n, hmem⟩, ?_⟩
  have h2n : (0 : ℝ) < 2 ^ n := by positivity
  have hval : dyadicToReal ⟨(k : ℚ) * ((2 : ℚ)⁻¹) ^ n, hmem⟩ = (k : ℝ) * ((2 : ℝ) ^ n)⁻¹ := by
    have h : dyadicToReal ⟨(k : ℚ) * ((2 : ℚ)⁻¹) ^ n, hmem⟩
        = (((k : ℚ) * ((2 : ℚ)⁻¹) ^ n : ℚ) : ℝ) := rfl
    rw [h, Rat.cast_mul, Rat.cast_pow, Rat.cast_inv, Rat.cast_intCast, Rat.cast_ofNat, inv_pow]
  rw [Real.dist_eq, hval]
  have hfl : (k : ℝ) ≤ x * 2 ^ n := Int.floor_le _
  have hfu : x * 2 ^ n < (k : ℝ) + 1 := Int.lt_floor_add_one _
  have hinv : ((2 : ℝ) ^ n)⁻¹ < ε := by
    have h12 : ((1 : ℝ) / 2) ^ n = ((2 : ℝ) ^ n)⁻¹ := by rw [div_pow, one_pow, one_div]
    rw [← h12]; exact hn
  have hlo : (k : ℝ) * ((2 : ℝ) ^ n)⁻¹ ≤ x := by
    have := mul_le_mul_of_nonneg_right hfl (by positivity : (0 : ℝ) ≤ ((2 : ℝ) ^ n)⁻¹)
    rwa [mul_assoc, mul_inv_cancel₀ (ne_of_gt h2n), mul_one] at this
  have hhi : x < (k : ℝ) * ((2 : ℝ) ^ n)⁻¹ + ((2 : ℝ) ^ n)⁻¹ := by
    have := mul_lt_mul_of_pos_right hfu (by positivity : (0 : ℝ) < ((2 : ℝ) ^ n)⁻¹)
    rwa [mul_assoc, mul_inv_cancel₀ (ne_of_gt h2n), mul_one, add_mul, one_mul] at this
  rw [abs_lt]
  exact ⟨by linarith, by linarith⟩

instance : NumBase Dyadic where
  toReal := dyadicToReal
  inj_toReal := dyadicToReal_injective
  countable := inferInstance

instance : DenseNumBase Dyadic where
  dense_toReal := denseRange_dyadicToReal

end TLT.Capacity
